,
{//Room index: Template
  name:"",
  image:"",
  description:"",
  doors:[
    {
      keys[],
      leadsTo:0
    }
  ],
  tasks:[
    {
      name:"",
      keys:[],
      results:[
        {
          message:"",
          chance:100,
          isRepeatable:false,
          item:{
              snowflake:"",
              name:"",
              description:"",
              actions:[
                {
                  snowflake:"",
                  roomIndex:0,
                  name:""
                }
              ]
            }
        }
      ]
    }
  ]
}
